### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by ClemensLinnhoff** [DLR-TS/OSTAR-Quickstart#5]
I installed OSTAR according to the Readme on Ubuntu 22.04.
I ran the first example with `./run.sh --visual` and selected 0.

A Carla window opens and the map seems to be loaded.
But then I get the following error:

```
Could not find given file path: ObjectBasedGenericPerceptionObjectModel.fmu Will try this path as a local path direct in OSMP environment.
Running in OSMP mode.
File does not exist: /home/carla/ObjectBasedGenericPerceptionObjectModel.fmu
[Fatal] [Sun Oct 27 15:40:30 2024
] /osmpservice/lib/FMI4cpp/src/fmi2/fmu.cpp:55: Failed to extract FMU '/home/carla/ObjectBasedGenericPerceptionObjectModel.fmu'!
channel is ready for work
Unexpected error in RPC handling
Error in initialization of simulation interfaces.
TS: Timestamp(frame=21,elapsed_seconds=1.282618,delta_seconds=0.050000,platform_timestamp=7518.846620)
TS: Timestamp(frame=22,elapsed_seconds=1.332618,delta_seconds=0.050000,platform_timestamp=7518.851661)
Traceback (most recent call last):
  File "app/scenario_runner/scenario_runner.py", line 431, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/carla/app/scenario_runner/srunner/scenariomanager/scenario_manager.py", line 143, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/carla/app/scenario_runner/srunner/scenariomanager/scenario_manager.py", line 196, in _tick_scenario
    self.client_socket.sendall(struct.pack('d', timestamp.delta_seconds))
BrokenPipeError: [Errno 32] Broken pipe
[Errno 32] Broken pipe
```

I thought, maybe I need to build the FMU first, so I executed `build_1-3-generic.sh` in the models folder. It builds, but then I get errors here, too:

```
 => [internal] load build definition from Dockerfile                                                                                   0.1s
 => => transferring dockerfile: 209B                                                                                                   0.0s
 => ERROR [internal] load metadata for docker.io/library/ostar:model_builder                                                           0.9s
------
 > [internal] load metadata for docker.io/library/ostar:model_builder:
------
Dockerfile:1
--------------------
   1 | >>> FROM ostar:model_builder
   2 |     LABEL maintainer="bjoern.bahn@dlr.de"
   3 |     
--------------------
ERROR: failed to solve: ostar:model_builder: failed to resolve source metadata for docker.io/library/ostar:model_builder: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Unable to find image 'ostar:sl-1-3-object-based-generic-perception-object-model' locally
Error response from daemon: pull access denied for ostar, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error response from daemon: No such container: temp_model
Error response from daemon: No such container: temp_model
```

What am I doing wrong?
@bjoernbahn could you support here?

**Comment by ClemensLinnhoff** [comment]
I then tried the local build. And here the example seems to work.

**Comment by akloeker** [comment]
I made all examples work with these additional steps:

1. Build `DockerfileModelBuilder` locally: `docker build -f DockerfileModelBuilder -t bjoernbahndlr/ostar:model_builder util/dockerfiles`
2. Execute all `build*.sh` scripts in the `models` directory
3. Adjust the `docker run` command in `util/runSingleContainer.sh` to mount the built model .fmu files into the container
```
docker run --privileged --net=host --gpus all \
       --volume models/ReflectionBasedRadarModel.fmu:/home/carla/ReflectionBasedRadarModel.fmu \
       --volume models/ReflectionBasedLidarModel.fmu:/home/carla/ReflectionBasedLidarModel.fmu \
       --volume models/ObjectBasedGenericPerceptionObjectModel.fmu:/home/carla/ObjectBasedGenericPerceptionObjectModel.fmu \
       --volume models/ObjectBasedCameraModel.fmu:/home/carla/ObjectBasedCameraModel.fmu \
       --name ostar-single-container -e DISPLAY=$DISPLAY -it --mount type=bind,source="$input_abs_path",target=/home/carla/input --mount type=bind,source="$output_abs_path",target=/home/carla/output $IMAGE_NAME $ALL_PARAMETERS
```
4. Delete examples/00-opendrive-openscenario/configDistributedSimulation.yml
5. Give the user in the container write access to the `output` directory: chmod -R 777 ./output
6. Run the examples: `run.sh`

**Comment by bjoernbahn** [comment]
Hi Clemens,

currently there are some bugs in the main branch if it is just run and not build locally.
As @akloeker pointed out, you need to build locally to get the FMUs and delete the configDistributedSimulation.yml file.

I have to take a final look on the branch with the fixes and merge it into main. Should have merged earlier.
https://github.com/DLR-TS/OSTAR-Quickstart/tree/fix-container-and-implement-feedback

**Comment by bjoernbahn** [comment]
Check if the merge #6 solves your problems.
